# Generated by Django 3.1 on 2021-12-18 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Waiting", "Waiting"),
                            ("Failed", "Failed"),
                            ("Redirect to bank", "Redirect To Bank"),
                            ("Return from bank", "Return From Bank"),
                            ("Cancel by user", "Cancel By User"),
                            ("Expire gateway token", "Expire Gateway Token"),
                            ("Expire verify payment", "Expire Verify Payment"),
                            ("Complete", "Complete"),
                        ],
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "bank_type",
                    models.CharField(
                        choices=[("ZIBAL", "Zibal"), ("STRIPE", "Stripe")],
                        max_length=50,
                        verbose_name="Bank",
                    ),
                ),
                ("amount", models.CharField(max_length=10, verbose_name="Amount")),
                (
                    "transaction_code",
                    models.CharField(max_length=255, verbose_name="Transaction code"),
                ),
                (
                    "response_result",
                    models.TextField(blank=True, null=True, verbose_name="Bank result"),
                ),
                ("callback_url", models.TextField(verbose_name="Callback url")),
                (
                    "extra_information",
                    models.TextField(
                        blank=True, null=True, verbose_name="Extra information"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_record",
                        to="order.order",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment record",
                "verbose_name_plural": "Payment records",
            },
        ),
    ]
