# Generated by Django 3.1 on 2021-12-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrecord",
            name="amount",
            field=models.FloatField(max_length=10, verbose_name="Amount"),
        ),
    ]
