# Generated by Django 3.1 on 2021-12-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrecord",
            name="transaction_code",
            field=models.CharField(max_length=255, verbose_name="Transaction code"),
        ),
    ]
