# Generated by Django 3.1 on 2021-12-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_auto_20211222_2042"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("Failed", "Failed"),
                    ("Redirect to bank", "Redirect To Bank"),
                    ("Complete", "Complete"),
                ],
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
