# Generated by Django 3.1 on 2021-12-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_auto_20211213_1709"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentrecord",
            name="tracking_code",
        ),
    ]
