# Generated by Django 3.1 on 2021-12-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_remove_paymentrecord_tracking_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrecord",
            name="bank_type",
            field=models.CharField(
                choices=[("ZIBAL", "Zibal"), ("STRIPE", "Stripe")],
                max_length=50,
                verbose_name="Bank",
            ),
        ),
    ]
