# Generated by Django 3.1 on 2021-11-12 16:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211112_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_b',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
