# Generated by Django 3.1 on 2021-11-12 16:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_content_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_b',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
