# Generated by Django 3.1 on 2021-11-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211112_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_b',
        ),
    ]
