# Generated by Django 3.1 on 2021-09-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_no",
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
