# Generated by Django 3.1 on 2021-09-17 01:41

from django.db import migrations, models
import pyotp


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_auto_20210917_0137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="key",
            field=models.CharField(
                blank=True, default=pyotp.random_base32, max_length=40
            ),
        ),
    ]
