# Generated by Django 3.1 on 2021-11-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='operation',
            field=models.CharField(blank=True, choices=[('redirect', 'operation redirect'), ('seo_info', 'operation include SEO info')], max_length=100, null=True, verbose_name='operation of page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='redirect_status',
            field=models.IntegerField(blank=True, choices=[(301, '301:Permanent, Cacheable, Request GET/POST may change'), (302, '302:Temporary, not Cacheable by default, Request GET/POST may change'), (303, '303:Temporary, never Cacheable, Request always GET'), (307, '307:Temporary, not Cacheable by default, Request may not change'), (308, '308:Permanent, by default Cacheable, Request may not change')], null=True, verbose_name='redirect status code'),
        ),
    ]
