# Generated by Django 3.1 on 2021-12-13 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('placement_date', models.DateTimeField(verbose_name='Placement date')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('cancel_by_user', 'Cancel by user'), ('complete', 'Complete'), ('deliver', 'Deliver')], max_length=30, verbose_name='status')),
                ('bank_type', models.CharField(max_length=50, verbose_name='Bank')),
                ('tracking_code', models.CharField(max_length=255, verbose_name='Tracking code')),
                ('reference_number', models.CharField(max_length=255, unique=True, verbose_name='Reference number')),
                ('response_result', models.TextField(blank=True, null=True, verbose_name='Bank result')),
                ('extra_information', models.TextField(blank=True, null=True, verbose_name='Extra information')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
