# Generated by Django 3.1 on 2021-12-18 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placement_date", models.DateTimeField(verbose_name="Placement date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting_for_payment", "Waiting for payment"),
                            ("failed_payment", "Failed payment"),
                            ("cancel_order_by_user", "Cancel order by user"),
                            ("paid", "Paid"),
                            ("deliver", "Deliver"),
                            ("post", "Post"),
                        ],
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("IRR", "Rial"), ("IRT", "Toman"), ("cad", "cad")],
                        max_length=50,
                        verbose_name="Currency",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Amount")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
