# Generated by Django 3.1 on 2021-12-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("cancel_by_user", "Cancel by user"),
                    ("complete", "Complete"),
                    ("deliver", "Deliver"),
                    ("post", "Post"),
                ],
                max_length=30,
                verbose_name="status",
            ),
        ),
    ]
