# Generated by Django 3.1 on 2021-12-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_auto_20211217_1355"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting_for_payment", "Waiting for payment"),
                    ("failed_payment", "Failed payment"),
                    ("cancel_order_by_user", "Cancel order by user"),
                    ("paid", "Paid"),
                    ("deliver", "Deliver"),
                    ("post", "Post"),
                ],
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
